"""
Licensing & Provenance — embeds usage rights into generated assets.

Google's Generative AI Terms of Service grant users a royalty-free
license to use, reproduce, and distribute AI-generated content for
commercial purposes.  This module records that provenance so every
asset in AetherWave carries its own license chain.

What we embed:
  1. JPEG EXIF/XMP comments  — human-readable license in the image file
  2. LoreLedger.license      — machine-readable block in the MP3 metadata
  3. LICENSE_NOTICE.md        — top-level repo file explaining the terms

Key constraints from Google's Acceptable Use Policy:
  • No generating likenesses of real people
  • No generating real trademarks or logos
  • No deceptive or harmful content
  • All prompts in art_generator.py are written to enforce these rules
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# The canonical license text baked into every generated asset.
LICENSE_TEXT = (
    "This asset was generated by AetherWave using Google's Generative AI APIs "
    "(Imagen / Gemini / Lyria).  Per Google's Terms of Service, the creator "
    "is granted a royalty-free, non-exclusive license to use, reproduce, modify, "
    "and distribute this content for commercial and non-commercial purposes.  "
    "This content is NOT eligible for copyright registration as a purely "
    "AI-generated work in most jurisdictions.  Human creative direction "
    "(prompt engineering, curation, editing) may establish additional rights.  "
    "See https://ai.google.dev/terms for the latest terms."
)


class LicenseInfo(BaseModel):
    """Machine-readable license block embedded in Lore_Ledger and JPEG metadata."""

    license_type: str = "Google Generative AI — Royalty-Free Commercial Use"
    license_url: str = "https://ai.google.dev/terms"
    generator: str = "AetherWave Labs"
    art_type: str = ""
    station_name: str = ""
    artist_name: str = ""
    style_seed: str = ""
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    notice: str = LICENSE_TEXT

    @classmethod
    def for_generated_art(
        cls,
        art_type: str,
        station_name: str,
        artist_name: str = "",
        style_seed: str = "",
    ) -> LicenseInfo:
        return cls(
            art_type=art_type,
            station_name=station_name,
            artist_name=artist_name,
            style_seed=style_seed,
        )

    @classmethod
    def for_generated_audio(
        cls,
        station_name: str,
        artist_name: str,
        voice_seed: str = "",
    ) -> LicenseInfo:
        return cls(
            art_type="audio_track",
            station_name=station_name,
            artist_name=artist_name,
            style_seed=voice_seed,
        )


def stamp_license_metadata(image_path: Path, license_info: LicenseInfo) -> None:
    """
    Write the license info as a JPEG comment / XMP block.

    Uses Pillow to re-save the image with an EXIF UserComment containing
    the full license JSON.  This is non-destructive to the image data.
    """
    try:
        from PIL import Image

        import piexif

        img = Image.open(image_path)

        # Build EXIF with UserComment
        exif_dict = piexif.load(img.info.get("exif", b"")) if "exif" in img.info else {
            "0th": {}, "Exif": {}, "GPS": {}, "1st": {}
        }

        # Encode license as UserComment (ASCII)
        license_json = license_info.model_dump_json()
        user_comment = piexif.helper.UserComment.dump(license_json, encoding="unicode")
        exif_dict["Exif"][piexif.ExifIFD.UserComment] = user_comment

        # Also set ImageDescription for human-readable viewers
        exif_dict["0th"][piexif.ImageIFD.ImageDescription] = LICENSE_TEXT.encode("utf-8")

        exif_bytes = piexif.dump(exif_dict)
        img.save(str(image_path), "JPEG", exif=exif_bytes, quality=95)
        logger.info("License metadata stamped on %s", image_path.name)

    except ImportError:
        # Fallback: write a sidecar JSON if Pillow/piexif not available
        logger.warning("Pillow/piexif not installed — writing sidecar license file")
        sidecar = image_path.with_suffix(".license.json")
        sidecar.write_text(license_info.model_dump_json(indent=2), encoding="utf-8")

    except Exception as exc:
        logger.warning("Could not stamp license metadata on %s: %s", image_path, exc)
        # Non-fatal — the image is still usable
